### ISSUE TITLE
cpu usage at idle

### ISSUE THREAD

**Issue by areux** [Snowlabs/Jamyx#2] opened 2018-01-25 16:12 UTC
jam has 10%-15% cpu usage while just listening for new connections. I don't think this is normal.

**Comment by Javyre** [comment] 2018-01-25 22:49
I will look into this immediately. (I use jamyx full-time so this is worth looking at)

Any hunches as to why this is the case?

**Comment by Javyre** [comment] 2018-01-25 23:08
Do you think this is in any way related to #3?

**Comment by Javyre** [comment] 2018-01-26 00:02
I cant seem to reproduce this...
Can you send me details on reproducing the issue?
Also, copy the log output with maximum verbosity on (`-vvvvv`)

**Comment by areux** [comment] 2018-01-27 17:16
Sorry for the delay; this is the output from master with default config.json:
```
$ cargo run -- -vvvvv
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/jam -vvvvv`
version: 0.0.1
 Jan 27 19:43:23.379 INFO Logger init
 Jan 27 19:43:23.379 INFO Parsing config file at path: "config.json"
 Jan 27 19:43:23.379 INFO Init
 Jan 27 19:43:23.393 DEBG Starting jclient...
 Jan 27 19:43:23.410 INFO Port registered: `Jacon:PulseSink2 L`
 Jan 27 19:43:23.411 INFO Port registered: `Jacon:PulseSink2 R`
 Jan 27 19:43:23.411 INFO Port registered: `Jacon:MPD L`
 Jan 27 19:43:23.411 INFO Port registered: `Jacon:MPD R`
 Jan 27 19:43:23.411 INFO Reevaluating connections for port: `Jacon:PulseSink2 L`
 Jan 27 19:43:23.411 INFO Port registered: `Jacon:Mic M`
 Jan 27 19:43:23.411 INFO Port registered: `Jacon:PulseSink L`
 Jan 27 19:43:23.411 INFO Port registered: `Jacon:PulseSink R`
 Jan 27 19:43:23.412 INFO Port registered: `Jacon:PrivMPD L`
 Jan 27 19:43:23.412 INFO Port registered: `Jacon:PrivMPD R`
 Jan 27 19:43:23.412 INFO Port registered: `Jacon:PubMPD L`
 Jan 27 19:43:23.412 INFO Port registered: `Jacon:PubMPD R`
 Jan 27 19:43:23.412 INFO Port registered: `Jacon:PulseSink2 Out L`
 Jan 27 19:43:23.412 INFO Port registered: `Jacon:PulseSink2 Out R`
 Jan 27 19:43:23.412 INFO Port registered: `Jacon:MPD Out L`
 Jan 27 19:43:23.412 INFO Port registered: `Jacon:MPD Out R`
 Jan 27 19:43:23.412 INFO Port registered: `Jacon:Mic Out M`
 Jan 27 19:43:23.412 INFO Port registered: `Jacon:PulseSink Out L`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:PulseSink Out R`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:PrivMPD Out L`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:PrivMPD Out R`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:PubMPD Out L`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:PubMPD Out R`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:PUBLIC L`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:PUBLIC R`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:PRIVATE L`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:PRIVATE R`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:MASTER L`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:MASTER R`
 Jan 27 19:43:23.413 INFO Port registered: `Jacon:MONITOR L`
 Jan 27 19:43:23.414 INFO Port registered: `Jacon:MONITOR R`
 Jan 27 19:43:23.414 DEBG Starting Jacon...
 Jan 27 19:43:23.414 DEBG Starting Jamyxer...
 Jan 27 19:43:23.414 DEBG Starting server...
 Jan 27 19:43:23.414 DEBG Done Activation phase!
 Jan 27 19:43:23.414 INFO Reevaluating connections for port: `Jacon:PulseSink2 R`
 Jan 27 19:43:23.414 INFO Reevaluating connections for port: `Jacon:MPD L`
 Jan 27 19:43:23.414 INFO Reevaluating connections for port: `Jacon:MPD R`
 Jan 27 19:43:23.415 INFO Reevaluating connections for port: `Jacon:Mic M`
 Jan 27 19:43:23.415 INFO Reevaluating connections for port: `Jacon:PulseSink L`
 Jan 27 19:43:23.415 INFO Reevaluating connections for port: `Jacon:PulseSink R`
 Jan 27 19:43:23.415 INFO Reevaluating connections for port: `Jacon:PrivMPD L`
 Jan 27 19:43:23.416 INFO Reevaluating connections for port: `Jacon:PrivMPD R`
 Jan 27 19:43:23.416 INFO Reevaluating connections for port: `Jacon:PubMPD L`
 Jan 27 19:43:23.416 INFO Reevaluating connections for port: `Jacon:PubMPD R`
 Jan 27 19:43:23.416 INFO Reevaluating connections for port: `Jacon:PulseSink2 Out L`
 Jan 27 19:43:23.416 INFO Reevaluating connections for port: `Jacon:PulseSink2 Out R`
 Jan 27 19:43:23.416 INFO Reevaluating connections for port: `Jacon:MPD Out L`
 Jan 27 19:43:23.416 INFO Reevaluating connections for port: `Jacon:MPD Out R`
 Jan 27 19:43:23.416 INFO Reevaluating connections for port: `Jacon:Mic Out M`
 Jan 27 19:43:23.417 INFO Reevaluating connections for port: `Jacon:PulseSink Out L`
 Jan 27 19:43:23.417 INFO Reevaluating connections for port: `Jacon:PulseSink Out R`
 Jan 27 19:43:23.417 INFO Reevaluating connections for port: `Jacon:PrivMPD Out L`
 Jan 27 19:43:23.417 INFO Reevaluating connections for port: `Jacon:PrivMPD Out R`
 Jan 27 19:43:23.417 INFO Reevaluating connections for port: `Jacon:PubMPD Out L`
 Jan 27 19:43:23.417 INFO Reevaluating connections for port: `Jacon:PubMPD Out R`
 Jan 27 19:43:23.417 INFO Reevaluating connections for port: `Jacon:PUBLIC L`
 Jan 27 19:43:23.417 INFO Reevaluating connections for port: `Jacon:PUBLIC R`
 Jan 27 19:43:23.418 INFO Reevaluating connections for port: `Jacon:PRIVATE L`
 Jan 27 19:43:23.418 INFO Reevaluating connections for port: `Jacon:PRIVATE R`
 Jan 27 19:43:23.418 INFO Reevaluating connections for port: `Jacon:MASTER L`
 Jan 27 19:43:23.418 INFO Reevaluating connections for port: `Jacon:MASTER R`
 Jan 27 19:43:23.418 INFO Reevaluating connections for port: `Jacon:MONITOR L`
 Jan 27 19:43:23.418 INFO Reevaluating connections for port: `Jacon:MONITOR R`
 Jan 27 19:43:23.418 INFO Disconnecting all
 Jan 27 19:43:23.418 INFO Reconnecting all good
 Jan 27 19:43:23.418 DEBG Trying connection: `python2:out_jackaudiosink0_1` and `Jacon:MPD L`
 Jan 27 19:43:23.418 DEBG One or both of ports: `python2:out_jackaudiosink0_1` and `Jacon:MPD L` does not exist!
 Jan 27 19:43:23.418 DEBG Trying connection: `python2:out_jackaudiosink0_2` and `Jacon:MPD R`
 Jan 27 19:43:23.418 DEBG One or both of ports: `python2:out_jackaudiosink0_2` and `Jacon:MPD R` does not exist!
 Jan 27 19:43:23.419 DEBG Trying connection: `system:capture_1` and `Jacon:Mic M`
 Jan 27 19:43:23.419 DEBG Trying connection: `PulseAudio JACK Sink:front-left` and `Jacon:PulseSink L`
 Jan 27 19:43:23.419 DEBG Trying connection: `PulseAudio JACK Sink:front-right` and `Jacon:PulseSink R`
 Jan 27 19:43:23.419 DEBG Trying connection: `Jacon:MPD Out L` and `Jacon:PrivMPD L`
 Jan 27 19:43:23.419 DEBG Trying connection: `Jacon:MPD Out R` and `Jacon:PrivMPD R`
 Jan 27 19:43:23.419 DEBG Trying connection: `Jacon:MPD Out L` and `Jacon:PubMPD L`
 Jan 27 19:43:23.419 DEBG Trying connection: `Jacon:MPD Out R` and `Jacon:PubMPD R`
 Jan 27 19:43:23.419 DEBG Trying connection: `Jacon:MPD Out L` and `Jacon:PrivMPD L`
 Jan 27 19:43:23.419 ERRO PortAlreadyConnected("Jacon:MPD Out L", "Jacon:PrivMPD L")
 Jan 27 19:43:23.419 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.419 DEBG Trying connection: `Jacon:MPD Out L` and `Jacon:PubMPD L`
 Jan 27 19:43:23.419 ERRO PortAlreadyConnected("Jacon:MPD Out L", "Jacon:PubMPD L")
 Jan 27 19:43:23.420 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.420 DEBG Trying connection: `Jacon:MPD Out R` and `Jacon:PubMPD R`
 Jan 27 19:43:23.420 ERRO PortAlreadyConnected("Jacon:MPD Out R", "Jacon:PubMPD R")
 Jan 27 19:43:23.420 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.420 DEBG Trying connection: `Jacon:MPD Out R` and `Jacon:PrivMPD R`
 Jan 27 19:43:23.420 ERRO PortAlreadyConnected("Jacon:MPD Out R", "Jacon:PrivMPD R")
 Jan 27 19:43:23.420 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.420 DEBG Trying connection: `Jacon:PUBLIC L` and `PulseAudio JACK Source:front-left`
 Jan 27 19:43:23.420 DEBG One or both of ports: `Jacon:PUBLIC L` and `PulseAudio JACK Source:front-left` does not exist!
 Jan 27 19:43:23.420 DEBG Trying connection: `Jacon:PUBLIC R` and `PulseAudio JACK Source:front-right`
 Jan 27 19:43:23.420 DEBG One or both of ports: `Jacon:PUBLIC R` and `PulseAudio JACK Source:front-right` does not exist!
 Jan 27 19:43:23.420 DEBG Trying connection: `Jacon:MONITOR L` and `system:playback_1`
 Jan 27 19:43:23.421 DEBG Trying connection: `Jacon:MONITOR R` and `system:playback_2`
 Jan 27 19:43:23.421 DEBG => disabling connection check
 Jan 27 19:43:23.421 DEBG => enabling connection check
 Jan 27 19:43:23.421 DEBG Trying connection: `python2:out_jackaudiosink0_1` and `Jacon:MPD L`
 Jan 27 19:43:23.421 DEBG One or both of ports: `python2:out_jackaudiosink0_1` and `Jacon:MPD L` does not exist!
 Jan 27 19:43:23.421 DEBG Trying connection: `PulseAudio JACK Sink:front-left` and `Jacon:PulseSink L`
 Jan 27 19:43:23.421 ERRO PortAlreadyConnected("PulseAudio JACK Sink:front-left", "Jacon:PulseSink L")
 Jan 27 19:43:23.421 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.421 DEBG Trying connection: `Jacon:MPD Out L` and `Jacon:PrivMPD L`
 Jan 27 19:43:23.421 ERRO PortAlreadyConnected("Jacon:MPD Out L", "Jacon:PrivMPD L")
 Jan 27 19:43:23.421 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.421 DEBG Trying connection: `Jacon:MPD Out L` and `Jacon:PubMPD L`
 Jan 27 19:43:23.421 ERRO PortAlreadyConnected("Jacon:MPD Out L", "Jacon:PubMPD L")
 Jan 27 19:43:23.422 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.422 DEBG Trying connection: `Jacon:PUBLIC R` and `PulseAudio JACK Source:front-right`
 Jan 27 19:43:23.422 DEBG One or both of ports: `Jacon:PUBLIC R` and `PulseAudio JACK Source:front-right` does not exist!
 Jan 27 19:43:23.422 DEBG Trying connection: `system:capture_1` and `Jacon:Mic M`
 Jan 27 19:43:23.422 ERRO PortAlreadyConnected("system:capture_1", "Jacon:Mic M")
 Jan 27 19:43:23.422 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.422 DEBG Trying connection: `Jacon:MONITOR L` and `system:playback_1`
 Jan 27 19:43:23.422 ERRO PortAlreadyConnected("Jacon:MONITOR L", "system:playback_1")
 Jan 27 19:43:23.422 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.422 DEBG Trying connection: `python2:out_jackaudiosink0_2` and `Jacon:MPD R`
 Jan 27 19:43:23.422 DEBG One or both of ports: `python2:out_jackaudiosink0_2` and `Jacon:MPD R` does not exist!
 Jan 27 19:43:23.422 DEBG Trying connection: `Jacon:MONITOR R` and `system:playback_2`
 Jan 27 19:43:23.423 ERRO PortAlreadyConnected("Jacon:MONITOR R", "system:playback_2")
 Jan 27 19:43:23.423 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.423 DEBG Trying connection: `Jacon:MPD Out R` and `Jacon:PubMPD R`
 Jan 27 19:43:23.423 ERRO PortAlreadyConnected("Jacon:MPD Out R", "Jacon:PubMPD R")
 Jan 27 19:43:23.423 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.423 DEBG Trying connection: `Jacon:MPD Out R` and `Jacon:PrivMPD R`
 Jan 27 19:43:23.423 ERRO PortAlreadyConnected("Jacon:MPD Out R", "Jacon:PrivMPD R")
 Jan 27 19:43:23.423 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.423 DEBG Trying connection: `PulseAudio JACK Sink:front-right` and `Jacon:PulseSink R`
 Jan 27 19:43:23.423 ERRO PortAlreadyConnected("PulseAudio JACK Sink:front-right", "Jacon:PulseSink R")
 Jan 27 19:43:23.423 WARN FAILED! Rescheduling!
 Jan 27 19:43:23.423 DEBG Trying connection: `Jacon:PUBLIC L` and `PulseAudio JACK Source:front-left`
 Jan 27 19:43:23.424 DEBG One or both of ports: `Jacon:PUBLIC L` and `PulseAudio JACK Source:front-left` does not exist!
 stat: GOOD
  Jan 27 19:43:23.424 INFO Ports connected: `system:capture_1` and `Jacon:Mic M`
  Jan 27 19:43:23.424 DEBG GOOD: 
  Jan 27 19:43:23.424 DEBG Doing nothing
  Jan 27 19:43:23.424 INFO Ports connected: `PulseAudio JACK Sink:front-left` and `Jacon:PulseSink L`
  Jan 27 19:43:23.424 DEBG GOOD: 
  Jan 27 19:43:23.424 DEBG Doing nothing
  Jan 27 19:43:23.424 INFO Ports connected: `PulseAudio JACK Sink:front-right` and `Jacon:PulseSink R`
  Jan 27 19:43:23.424 DEBG GOOD: 
  Jan 27 19:43:23.424 DEBG Doing nothing
  Jan 27 19:43:23.424 INFO Ports connected: `Jacon:MPD Out L` and `Jacon:PrivMPD L`
  Jan 27 19:43:23.425 DEBG GOOD: 
  Jan 27 19:43:23.425 DEBG Doing nothing
  Jan 27 19:43:23.425 INFO Ports connected: `Jacon:MPD Out R` and `Jacon:PrivMPD R`
  Jan 27 19:43:23.425 DEBG GOOD: 
  Jan 27 19:43:23.425 DEBG Doing nothing
  Jan 27 19:43:23.425 INFO Ports connected: `Jacon:MPD Out L` and `Jacon:PubMPD L`
  Jan 27 19:43:23.425 DEBG GOOD: 
  Jan 27 19:43:23.425 DEBG Doing nothing
  Jan 27 19:43:23.426 INFO Ports connected: `Jacon:MPD Out R` and `Jacon:PubMPD R`
  Jan 27 19:43:23.426 DEBG GOOD: 
  Jan 27 19:43:23.426 DEBG Doing nothing
  Jan 27 19:43:23.426 INFO Ports connected: `Jacon:MONITOR L` and `system:playback_1`
  Jan 27 19:43:23.426 DEBG GOOD: 
  Jan 27 19:43:23.427 DEBG Doing nothing
  Jan 27 19:43:23.427 INFO Ports connected: `Jacon:MONITOR R` and `system:playback_2`
  Jan 27 19:43:23.427 DEBG GOOD: 
  Jan 27 19:43:23.427 DEBG Doing nothing
```
my own [config](https://ptpb.pw/NUuh/js)+[output](https://ptpb.pw/KZbD).
jack configurations (realtime):
```
<?xml version="1.0"?>
<!--
JACK settings, as persisted by D-Bus object.
You probably don't want to edit this because
it will be overwritten next time jackdbus saves.
-->
<!-- Fri Oct 20 20:16:56 2017 -->
<jack>
 <engine>
  <option name="driver">alsa</option>
  <option name="realtime">true</option>
  <option name="verbose">false</option>
  <option name="client-timeout">500</option>
 </engine>
 <drivers>
  <driver name="net">
  </driver>
  <driver name="netone">
  </driver>
  <driver name="alsa">
   <option name="device">hw:USB</option>
   <option name="capture">hw:USB</option>
   <option name="playback">hw:Headset</option>
   <option name="rate">48000</option>
   <option name="period">1024</option>
   <option name="nperiods">2</option>
   <option name="hwmon">false</option>
   <option name="hwmeter">false</option>
   <option name="duplex">true</option>
   <option name="softmode">false</option>
   <option name="monitor">false</option>
   <option name="dither">n</option>
   <option name="shorts">false</option>
  </driver>
  <driver name="loopback">
  </driver>
  <driver name="alsarawmidi">
  </driver>
  <driver name="dummy">
  </driver>
  <driver name="proxy">
  </driver>
 </drivers>
 <internals>
  <internal name="netmanager">
  </internal>
  <internal name="profiler">
  </internal>
 </internals>
</jack>
```

```
top - 19:58:03 up 4 days,  3:31, 23 users,  load average: 0.31, 0.46, 0.41
Tasks: 375 total,   1 running, 307 sleeping,   2 stopped,   0 zombie
%Cpu(s):  4.6 us,  0.6 sy,  0.0 ni, 94.7 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 32865572 total,  5231664 free, 11458788 used, 16175120 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 20946280 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND      
26590 x         20   0  141904  89576  88900 S  10.6  0.3   1:33.05 jam          
12919 z         20   0 12.472g 544940  61728 S   1.7  1.7  60:49.86 java         
  440 x         20   0  973044 116532  55128 S   1.0  0.4  39:01.89 X            
 8000 x         20   0 3119988 361616  92144 S   0.7  1.1 143:22.51 chrome       
```

**Comment by Javyre** [comment] 2018-01-27 23:24
So this issue also occurs with the default config?
Im looking into a way of logging the PID of each thread to narrow down the root of the problem...

Is this in any way related to #3 ?

**Comment by areux** [comment] 2018-01-28 00:24
Yes, it also happens with the default config.
I'm not sure if these are related or not. 
@Javyre, could you tell me which areas of the code do I need to look to investigate a fix? (both #2 and #3)

**Comment by Javyre** [comment] 2018-01-28 01:43
I finally reproduced the issue, it seems that when the issue only occurs when running jamyx on a development build.
`cago run` runs a dev build and then executes the unoptimized binary.

When I test with `cargo run` or or run a bin from the `debug` target, I get 20-22% CPU usage
This issue does not occur (at least for me) when running a release binary:
 `cargo run --release` or `cargo build --release` and running the compiled bin from `target/release/jam`

As for the cause of this issue, i am not sure yet... There might be some code being expanded from a macro in the jack process callback that is performance heavy...

This could also just be normal rust behaviour and not a bug at all...

**Comment by Javyre** [comment] 2018-01-28 01:47
Contributions would be very welcome, I have been working on other projects lately but I update this project every now and then since I use it everyday (mostly casual use). For #3, I have no idea where to look... we can continue the conversation on the #3 issue. This is a pretty important issue to solve...

**Comment by areux** [comment] 2018-01-28 02:06
fixed; thanks.

**Comment by Javyre** [comment] 2018-01-28 02:13
apparently, according to [this post](https://internals.rust-lang.org/t/default-opt-level-for-release-builds/4581), cargo targets change the optimization level of the IR through Clang... Im assuming debug targetted builds dont get any optimization and thats enough to make it ~20 times heavier process

Closing issue as this is technically not a bug

**Closed as completed by Javyre** 2018-01-28 02:13 UTC
